export interface BulkBusiness {
	name: string;
	industry: string;
	city: string;
	state: string;
	phone: string;
	site: string;
}

export interface BulkTemplate {
	id: string;
	title: string;
	industry: string;
	glowColor: "blue" | "purple" | "green" | "orange" | "pink" | "cyan";
	businesses: BulkBusiness[];
}

/** Serialise a business array to the pipe-delimited intake format */
export function serialiseTemplate(businesses: BulkBusiness[]): string {
	return businesses
		.map(
			(b) =>
				`${b.name} | ${b.industry} | ${b.city}, ${b.state} | ${b.phone}${b.site ? ` | ${b.site}` : ""}`,
		)
		.join("\n");
}

export const BULK_TEMPLATES: BulkTemplate[] = [
	{
		id: "florida-plumbers",
		title: "10 Florida Plumbers",
		industry: "plumbing",
		glowColor: "blue",
		businesses: [
			{
				name: "Sunshine State Plumbing",
				industry: "plumbing",
				city: "Orlando",
				state: "FL",
				phone: "555-204-0118",
				site: "",
			},
			{
				name: "Bay Area Pipe Pros",
				industry: "plumbing",
				city: "Tampa",
				state: "FL",
				phone: "555-317-0243",
				site: "https://bayareapipepros.com",
			},
			{
				name: "River City Plumbing Co.",
				industry: "plumbing",
				city: "Jacksonville",
				state: "FL",
				phone: "555-481-0362",
				site: "",
			},
			{
				name: "South Beach Drains & More",
				industry: "plumbing",
				city: "Miami",
				state: "FL",
				phone: "555-592-0477",
				site: "",
			},
			{
				name: "Palm City Plumbing LLC",
				industry: "plumbing",
				city: "Fort Lauderdale",
				state: "FL",
				phone: "555-638-0519",
				site: "https://palmcityplumbing.net",
			},
			{
				name: "Gulf Coast Plumbing Services",
				industry: "plumbing",
				city: "Sarasota",
				state: "FL",
				phone: "555-714-0628",
				site: "",
			},
			{
				name: "Emerald Coast Plumbers",
				industry: "plumbing",
				city: "Pensacola",
				state: "FL",
				phone: "555-823-0741",
				site: "",
			},
			{
				name: "Treasure Coast Plumbing",
				industry: "plumbing",
				city: "Port St. Lucie",
				state: "FL",
				phone: "555-904-0856",
				site: "https://tcplumbing.com",
			},
			{
				name: "Space Coast Pipe & Drain",
				industry: "plumbing",
				city: "Brevard",
				state: "FL",
				phone: "555-167-0923",
				site: "",
			},
			{
				name: "Gator Plumbing Inc.",
				industry: "plumbing",
				city: "Gainesville",
				state: "FL",
				phone: "555-279-0034",
				site: "",
			},
		],
	},
	{
		id: "texas-roofers",
		title: "8 Texas Roofers",
		industry: "roofing",
		glowColor: "orange",
		businesses: [
			{
				name: "Lone Star Roofing Co.",
				industry: "roofing",
				city: "Houston",
				state: "TX",
				phone: "555-312-0147",
				site: "",
			},
			{
				name: "Storm Shield Roofing",
				industry: "roofing",
				city: "Dallas",
				state: "TX",
				phone: "555-428-0253",
				site: "https://stormshieldroofing.com",
			},
			{
				name: "Texas Sky Roofers",
				industry: "roofing",
				city: "San Antonio",
				state: "TX",
				phone: "555-534-0369",
				site: "",
			},
			{
				name: "Alamo Roofing & Restoration",
				industry: "roofing",
				city: "Austin",
				state: "TX",
				phone: "555-641-0472",
				site: "",
			},
			{
				name: "Panhandle Peak Roofing",
				industry: "roofing",
				city: "Amarillo",
				state: "TX",
				phone: "555-758-0581",
				site: "https://panhandlepeakroofing.net",
			},
			{
				name: "Gulf Winds Roofing LLC",
				industry: "roofing",
				city: "Corpus Christi",
				state: "TX",
				phone: "555-867-0694",
				site: "",
			},
			{
				name: "Brazos Valley Roof Pros",
				industry: "roofing",
				city: "Waco",
				state: "TX",
				phone: "555-923-0718",
				site: "",
			},
			{
				name: "North Texas Roofing Experts",
				industry: "roofing",
				city: "Fort Worth",
				state: "TX",
				phone: "555-136-0825",
				site: "https://northtxroofing.com",
			},
		],
	},
	{
		id: "california-landscapers",
		title: "12 California Landscapers",
		industry: "landscaping",
		glowColor: "green",
		businesses: [
			{
				name: "SoCal Drought-Smart Landscapes",
				industry: "landscaping",
				city: "Los Angeles",
				state: "CA",
				phone: "555-218-0134",
				site: "",
			},
			{
				name: "Bay Breeze Lawn & Garden",
				industry: "landscaping",
				city: "San Francisco",
				state: "CA",
				phone: "555-347-0261",
				site: "https://baybreezelandscape.com",
			},
			{
				name: "Valley Verde Landscaping",
				industry: "landscaping",
				city: "Fresno",
				state: "CA",
				phone: "555-453-0378",
				site: "",
			},
			{
				name: "Pacific Coast Grounds",
				industry: "landscaping",
				city: "San Diego",
				state: "CA",
				phone: "555-569-0482",
				site: "",
			},
			{
				name: "Inland Empire Lawn Care",
				industry: "landscaping",
				city: "Riverside",
				state: "CA",
				phone: "555-672-0597",
				site: "https://ielawncare.com",
			},
			{
				name: "Gold Rush Garden Services",
				industry: "landscaping",
				city: "Sacramento",
				state: "CA",
				phone: "555-784-0613",
				site: "",
			},
			{
				name: "Peninsula Pro Landscaping",
				industry: "landscaping",
				city: "San Jose",
				state: "CA",
				phone: "555-891-0724",
				site: "",
			},
			{
				name: "Napa Valley Grounds & Garden",
				industry: "landscaping",
				city: "Napa",
				state: "CA",
				phone: "555-913-0831",
				site: "https://napagardens.net",
			},
			{
				name: "Redwood Roots Landscaping",
				industry: "landscaping",
				city: "Santa Rosa",
				state: "CA",
				phone: "555-124-0947",
				site: "",
			},
			{
				name: "Desert Bloom Xeriscaping",
				industry: "landscaping",
				city: "Palm Springs",
				state: "CA",
				phone: "555-237-0053",
				site: "",
			},
			{
				name: "Silicon Valley Green Spaces",
				industry: "landscaping",
				city: "Sunnyvale",
				state: "CA",
				phone: "555-341-0162",
				site: "https://svgreenspaces.com",
			},
			{
				name: "Coastal Canopy Lawn & Landscape",
				industry: "landscaping",
				city: "Santa Barbara",
				state: "CA",
				phone: "555-456-0278",
				site: "",
			},
		],
	},
	{
		id: "ohio-hvac",
		title: "6 Ohio HVAC Companies",
		industry: "hvac",
		glowColor: "cyan",
		businesses: [
			{
				name: "Buckeye Comfort Systems",
				industry: "hvac",
				city: "Columbus",
				state: "OH",
				phone: "555-213-0146",
				site: "",
			},
			{
				name: "Lake Erie Heating & Air",
				industry: "hvac",
				city: "Cleveland",
				state: "OH",
				phone: "555-329-0254",
				site: "https://lakeeriehvac.com",
			},
			{
				name: "Queen City Climate Control",
				industry: "hvac",
				city: "Cincinnati",
				state: "OH",
				phone: "555-437-0361",
				site: "",
			},
			{
				name: "Glass City HVAC Services",
				industry: "hvac",
				city: "Toledo",
				state: "OH",
				phone: "555-546-0473",
				site: "https://glasscityhvac.net",
			},
			{
				name: "Mahoning Valley Mechanical",
				industry: "hvac",
				city: "Youngstown",
				state: "OH",
				phone: "555-651-0584",
				site: "",
			},
			{
				name: "Dayton Air Experts",
				industry: "hvac",
				city: "Dayton",
				state: "OH",
				phone: "555-768-0692",
				site: "",
			},
		],
	},
	{
		id: "arizona-pool-services",
		title: "10 Arizona Pool Services",
		industry: "pool service",
		glowColor: "blue",
		businesses: [
			{
				name: "Desert Oasis Pool Care",
				industry: "pool service",
				city: "Phoenix",
				state: "AZ",
				phone: "555-214-0137",
				site: "",
			},
			{
				name: "Sonoran Pool Pros",
				industry: "pool service",
				city: "Tucson",
				state: "AZ",
				phone: "555-328-0248",
				site: "https://sonoranpoolpros.com",
			},
			{
				name: "Valley of the Sun Pool Service",
				industry: "pool service",
				city: "Scottsdale",
				state: "AZ",
				phone: "555-436-0352",
				site: "",
			},
			{
				name: "Mesa Blue Pool Maintenance",
				industry: "pool service",
				city: "Mesa",
				state: "AZ",
				phone: "555-547-0461",
				site: "https://mesabluepools.com",
			},
			{
				name: "Chandler Crystal Clear Pools",
				industry: "pool service",
				city: "Chandler",
				state: "AZ",
				phone: "555-659-0574",
				site: "",
			},
			{
				name: "Gilbert Pool & Spa Experts",
				industry: "pool service",
				city: "Gilbert",
				state: "AZ",
				phone: "555-762-0683",
				site: "",
			},
			{
				name: "Peoria Pool Works",
				industry: "pool service",
				city: "Peoria",
				state: "AZ",
				phone: "555-871-0795",
				site: "https://peoriapoolworks.net",
			},
			{
				name: "Glendale Pool Service Co.",
				industry: "pool service",
				city: "Glendale",
				state: "AZ",
				phone: "555-983-0814",
				site: "",
			},
			{
				name: "Tempe Aqua Care",
				industry: "pool service",
				city: "Tempe",
				state: "AZ",
				phone: "555-197-0923",
				site: "",
			},
			{
				name: "Sedona Springs Pool Cleaning",
				industry: "pool service",
				city: "Sedona",
				state: "AZ",
				phone: "555-213-0036",
				site: "https://sedonasprings.com",
			},
		],
	},
	{
		id: "colorado-painters",
		title: "8 Colorado Painters",
		industry: "painting",
		glowColor: "purple",
		businesses: [
			{
				name: "Mile High Painting Co.",
				industry: "painting",
				city: "Denver",
				state: "CO",
				phone: "555-312-0148",
				site: "",
			},
			{
				name: "Pikes Peak Painters",
				industry: "painting",
				city: "Colorado Springs",
				state: "CO",
				phone: "555-427-0259",
				site: "https://pikespeakpainters.com",
			},
			{
				name: "Boulder Brush & Roll",
				industry: "painting",
				city: "Boulder",
				state: "CO",
				phone: "555-534-0363",
				site: "",
			},
			{
				name: "Rocky Mountain Pro Painters",
				industry: "painting",
				city: "Fort Collins",
				state: "CO",
				phone: "555-641-0471",
				site: "https://rmppropainters.net",
			},
			{
				name: "Summit Coat Painting",
				industry: "painting",
				city: "Breckenridge",
				state: "CO",
				phone: "555-758-0586",
				site: "",
			},
			{
				name: "Cherry Creek Painting Services",
				industry: "painting",
				city: "Aurora",
				state: "CO",
				phone: "555-864-0692",
				site: "",
			},
			{
				name: "Grand Junction Color Works",
				industry: "painting",
				city: "Grand Junction",
				state: "CO",
				phone: "555-972-0714",
				site: "https://gjcolorworks.com",
			},
			{
				name: "High Country Interior Finishes",
				industry: "painting",
				city: "Aspen",
				state: "CO",
				phone: "555-183-0827",
				site: "",
			},
		],
	},
	{
		id: "new-york-electricians",
		title: "5 New York Electricians",
		industry: "electrical",
		glowColor: "orange",
		businesses: [
			{
				name: "Empire State Electric",
				industry: "electrical",
				city: "New York",
				state: "NY",
				phone: "555-412-0163",
				site: "",
			},
			{
				name: "Buffalo Bright Electrical",
				industry: "electrical",
				city: "Buffalo",
				state: "NY",
				phone: "555-527-0274",
				site: "https://buffalobright.com",
			},
			{
				name: "Rochester Residential Electric",
				industry: "electrical",
				city: "Rochester",
				state: "NY",
				phone: "555-634-0381",
				site: "",
			},
			{
				name: "Albany Current Electrical Co.",
				industry: "electrical",
				city: "Albany",
				state: "NY",
				phone: "555-748-0492",
				site: "https://albanycurrentelectric.net",
			},
			{
				name: "Long Island Wire & Panel",
				industry: "electrical",
				city: "Hempstead",
				state: "NY",
				phone: "555-856-0517",
				site: "",
			},
		],
	},
	{
		id: "nevada-concrete",
		title: "10 Nevada Concrete Contractors",
		industry: "concrete",
		glowColor: "pink",
		businesses: [
			{
				name: "Desert Slab Concrete Works",
				industry: "concrete",
				city: "Las Vegas",
				state: "NV",
				phone: "555-214-0152",
				site: "",
			},
			{
				name: "Sierra Concrete Solutions",
				industry: "concrete",
				city: "Reno",
				state: "NV",
				phone: "555-328-0263",
				site: "https://sierraconcretenv.com",
			},
			{
				name: "Henderson Hardscape & Concrete",
				industry: "concrete",
				city: "Henderson",
				state: "NV",
				phone: "555-436-0374",
				site: "",
			},
			{
				name: "Nevada Pro Driveways",
				industry: "concrete",
				city: "North Las Vegas",
				state: "NV",
				phone: "555-547-0481",
				site: "https://nevadaprodriveways.net",
			},
			{
				name: "Sparks Concrete & Foundations",
				industry: "concrete",
				city: "Sparks",
				state: "NV",
				phone: "555-659-0592",
				site: "",
			},
			{
				name: "Basin & Range Flatwork",
				industry: "concrete",
				city: "Carson City",
				state: "NV",
				phone: "555-762-0613",
				site: "",
			},
			{
				name: "Sun City Concrete Contractors",
				industry: "concrete",
				city: "Summerlin",
				state: "NV",
				phone: "555-871-0724",
				site: "https://suncityconcrete.com",
			},
			{
				name: "Mojave Slab & Foundation Co.",
				industry: "concrete",
				city: "Pahrump",
				state: "NV",
				phone: "555-983-0835",
				site: "",
			},
			{
				name: "High Desert Driveway Pros",
				industry: "concrete",
				city: "Elko",
				state: "NV",
				phone: "555-197-0946",
				site: "",
			},
			{
				name: "Las Vegas Stamped Concrete",
				industry: "concrete",
				city: "Las Vegas",
				state: "NV",
				phone: "555-213-0057",
				site: "https://lvstampedconcrete.com",
			},
		],
	},
];
